var flagData = {
  india: "🇮🇳",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  southAfrica: "🇿🇦",
  australia: "🇦🇺",
  newZealand: "🇳🇿",
  pakistan: "🇵🇰",
  westIndies: "",
  shriLanka: "🇱🇰",
};

var batsman = {
  1: {
    name: "Rohit Sharma",
    noMatches: 389,
    noCatches: 168,
    avg: 43.04,
    noFifties: 83,
    strikeRate: 94.88,
    team: "india",
  },
  2: {
    name: "Virat Kohli",
    noMatches: 445,
    noCatches: 270,
    avg: 54.3,
    noFifties: 118,
    strikeRate: 95.85,
    team: "india",
  },
  3: {
    name: "Joe Root",
    noMatches: 293,
    noCatches: 237,
    avg: 45.73,
    noFifties: 90,
    strikeRate: 89.38,
    team: "england",
  },
  4: {
    name: "Jos Buttler",
    noMatches: 289,
    noCatches: 361,
    avg: 35.52,
    noFifties: 53,
    strikeRate: 105.36,
    team: "england",
  },
  5: {
    name: "Q. De Kock",
    noMatches: 238,
    noCatches: 433,
    avg: 39.43,
    noFifties: 59,
    strikeRate: 100.54,
    team: "southAfrica",
  },
  6: {
    name: "Faf Du Plessis",
    noMatches: 262,
    noCatches: 168,
    avg: 41,
    noFifties: 66,
    strikeRate: 89.76,
    team: "southAfrica",
  },
  7: {
    name: "Steve Smith",
    noMatches: 257,
    noCatches: 230,
    avg: 44.03,
    noFifties: 60,
    strikeRate: 89.92,
    team: "australia",
  },
  8: {
    name: "David Warner",
    noMatches: 302,
    noCatches: 172,
    avg: 42,
    noFifties: 74,
    strikeRate: 102.89,
    team: "australia",
  },
  9: {
    name: "Kane Williamson",
    noMatches: 280,
    noCatches: 166,
    avg: 44.6,
    noFifties: 86,
    strikeRate: 85.83,
    team: "newZealand",
  },
  10: {
    name: "Ross Taylor",
    noMatches: 443,
    noCatches: 344,
    avg: 40.06,
    noFifties: 93,
    strikeRate: 88.46,
    team: "newZealand",
  },
  11: {
    name: "Babar Azam",
    noMatches: 188,
    noCatches: 96,
    avg: 48.64,
    noFifties: 59,
    strikeRate: 91.17,
    team: "pakistan",
  },
  12: {
    name: "Shoaib Malik",
    noMatches: 446,
    noCatches: 166,
    avg: 33.63,
    noFifties: 61,
    strikeRate: 84.4,
    team: "pakistan",
  },
  13: {
    name: "Chris Gayle",
    noMatches: 483,
    noCatches: 240,
    avg: 35.97,
    noFifties: 105,
    strikeRate: 94.98,
    team: "westIndies",
  },
  14: {
    name: "Darren Bravo",
    noMatches: 196,
    noCatches: 89,
    avg: 28.78,
    noFifties: 32,
    strikeRate: 73.88,
    team: "westIndies",
  },
  15: {
    name: "Dinesh Chandimal",
    noMatches: 274,
    noCatches: 174,
    avg: 30.71,
    noFifties: 49,
    strikeRate: 75.63,
    team: "sriLanka",
  },
  16: {
    name: "Kusal Parera",
    noMatches: 189,
    noCatches: 82,
    avg: 29.71,
    noFifties: 34,
    strikeRate: 98.61,
    team: "sriLanka",
  },
};

var bowlers = {
  1: {
    name: "Jasprit Bumrah",
    noMatches: 146,
    noCatches: 30,
    economy: 4.6,
    noWickets: 275,
    noFivers: 7,
    team: "india",
  },
  2: {
    name: "R. Ashwin",
    noMatches: 241,
    noCatches: 66,
    economy: 4.83,
    noWickets: 624,
    noFivers: 30,
    team: "india",
  },
  3: {
    name: "James Anderson",
    noMatches: 379,
    noCatches: 155,
    economy: 5.19,
    noWickets: 919,
    noFivers: 33,
    team: "england",
  },
  4: {
    name: "Adil Rashid",
    noMatches: 199,
    noCatches: 56,
    economy: 5.59,
    noWickets: 293,
    noFivers: 4,
    team: "england",
  },
  5: {
    name: "Kagiso Rabada",
    noMatches: 169,
    noCatches: 61,
    economy: 5.62,
    noWickets: 388,
    noFivers: 11,
    team: "southAfrica",
  },
  6: {
    name: "Keshav Maharaj",
    noMatches: 59,
    noCatches: 16,
    economy: 4.55,
    noWickets: 154,
    noFivers: 7,
    team: "southAfrica",
  },
  7: {
    name: "Mitchell Starc",
    noMatches: 208,
    noCatches: 77,
    economy: 5.33,
    noWickets: 480,
    noFivers: 21,
    team: "australia",
  },
  8: {
    name: "Pat Cummins",
    noMatches: 140,
    noCatches: 42,
    economy: 5,
    noWickets: 317,
    noFivers: 6,
    team: "australia",
  },
  9: {
    name: "Trent Boult",
    moMatches: 210,
    noCatches: 89,
    economy: 5.36,
    noWickets: 523,
    noFivers: 13,
    team: "newZealand",
  },
  10: {
    name: "Tim Southee",
    moMatches: 314,
    noCatches: 146,
    economy: 5.54,
    noWickets: 615,
    noFivers: 16,
    team: "newZealand",
  },
  11: {
    name: "Hasan Ali",
    noMatches: 120,
    noCatches: 28,
    economy: 5.7,
    noWickets: 212,
    noFivers: 9,
    team: "pakistan",
  },
  12: {
    name: "Shaheen Afridi",
    noMatches: 84,
    noCatches: 13,
    economy: 5.47,
    noWickets: 170,
    noFivers: 5,
    team: "pakistan",
  },
  13: {
    name: " Kemar Roach",
    noMatches: 170,
    noCatches: 39,
    economy: 5.13,
    noWickets: 365,
    noFivers: 12,
    team: "westIndies",
  },
  14: {
    name: " D.J Bravo ",
    noMatches: 295,
    noCatches: 158,
    economy: 5.56,
    noWickets: 363,
    noFivers: 3,
    team: "westIndies",
  },
  15: {
    name: "Suranga Lakmal",
    noMatches: 164,
    noCatches: 43,
    economy: 5.99,
    noWickets: 285,
    noFivers: 4,
    team: "sriLanka",
  },
  16: {
    name: "Thisara Perera",
    noMatches: 256,
    noCatches: 93,
    economy: 6.42,
    noWickets: 237,
    noFivers: 4,
    team: "sriLanka",
  },
};

var allRounders = {
  1: {
    name: "Ravindra Jadeja",
    noMatches: 279,
    strikeRate: 86.87,
    economy: 4.78,
    noWickets: 461,
    avg: 27.89,
    team: "india",
  },
  2: {
    name: "Ben Stokes",
    noMatches: 206,
    strikeRate: 96.77,
    economy: 6.03,
    noWickets: 256,
    avg: 32.53,
    team: "england",
  },
  3: {
    name: "Chris Morris",
    noMatches: 69,
    strikeRate: 92.87,
    economy: 6.12,
    noWickets: 94,
    avg: 31.77,
    team: "southAfrica",
  },
  4: {
    name: "Glenn Maxwell",
    noMatches: 202,
    strikeRate: 113,
    economy: 5.84,
    noWickets: 92,
    avg: 30.38,
    team: "australia",
  },
  5: {
    name: "James Neesham",
    noMatches: 116,
    strikeRate: 105.25,
    economy: 6.34,
    noWickets: 103,
    avg: 28.11,
    team: "newZealand",
  },
  6: {
    name: "Mohammad Hafeez",
    noMatches: 392,
    strikeRate: 84.88,
    economy: 4.48,
    noWickets: 253,
    avg: 32.33,
    team: "pakistan",
  },
  7: {
    name: "Jason Holder",
    noMatches: 203,
    strikeRate: 91.69,
    economy: 5.4,
    noWickets: 300,
    avg: 24.62,
    team: "westIndies",
  },
  8: {
    name: "Angelo Mathews",
    noMatches: 387,
    strikeRate: 83.17,
    economy: 4.76,
    noWickets: 191,
    avg: 37.41,
    team: "sriLanka",
  },
};
