// //Batsman:
// {
//     name: '',
//     noMatches: ,
//     noCatches: ,
//     avg: ,
//     noFifties: ,
//     strikeRate: ,
//     team: '',
// }

// //Bowlers:
// {
//     name: '',
//     noMatches: ,
//     noCatches: ,
//     economy: ,
//     noWickets: ,
//     noFivers: ,
//     team: '',
// }

// //All Rounders:
// {
//     name: '',
//     noMatches: ,
//     strikeRate: ,
//     economy: ,
//     noWickets: ,
//     avg: ,
//     team: '',
// }

var flagData = {
    'india': '🇮🇳',
    'england': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'southAfrica': '🇿🇦',
    'australia': '🇦🇺',
    'newZealand': '🇳🇿',
}

var batsman = {
    1:{
        name: 'Rohit Sharma',
        noMatches: 389,
        noCatches: 168,
        avg: 43.04,
        noFifties: 83,
        strikeRate: 94.88,
        team: 'india',
    },
    2:{
        name: 'Virat Kohli',
        noMatches: 445,
        noCatches: 270,
        avg: 54.3,
        noFifties: 118,
        strikeRate: 95.85,
        team: 'india',
    },
    3:{
        name: 'Joe Root',
        noMatches: 293,
        noCatches: 237,
        avg: 45.73,
        noFifties: 90,
        strikeRate: 89.38,
        team: 'england',
    },
    4:{
        name: 'Jos Buttler',
        noMatches: 289,
        noCatches: 361,
        avg: 35.52,
        noFifties: 53,
        strikeRate: 105.36,
        team: 'england',
    },
    5:{
        name: 'Q. De Kock',
        noMatches: 238,
        noCatches: 433,
        avg: 39.43,
        noFifties: 59,
        strikeRate: 100.54,
        team: 'southAfrica',
    },
    6:{
        name: 'Faf Du Plessis',
        noMatches: 262,
        noCatches: 168,
        avg: 41,
        noFifties: 66,
        strikeRate: 89.76,
        team: 'southAfrica',
    },
    7:{
        name: 'Steve Smith',
        noMatches: 257,
        noCatches: 230,
        avg: 44.03,
        noFifties: 60,
        strikeRate: 89.92,
        team: 'australia',
    },
    8:{
        name: 'David Warner',
        noMatches: 302,
        noCatches: 172,
        avg: 42,
        noFifties: 74,
        strikeRate: 102.89,
        team: 'australia',
    },
    9:{
        name: 'Kane Williamson',
        noMatches: 280,
        noCatches: 166,
        avg: 44.6,
        noFifties:86 ,
        strikeRate: 85.83,
        team: 'newZealand',
    },
    10:{
        name: 'Ross Taylor',
        noMatches: 443,
        noCatches: 344,
        avg: 40.06,
        noFifties: 93,
        strikeRate: 88.46,
        team: 'newZealand',
    },
}

var bowlers = {
    1:{
        name: 'Jasprit Bumrah',
        noMatches: 146,
        noCatches: 30,
        economy: 4.6,
        noWickets: 275,
        noFivers: 7,
        team: 'india'
    },
    2:{
        name: 'R. Ashwin',
        noMatches: 241,
        noCatches: 66,
        economy: 4.83,
        noWickets: 624,
        noFivers: 30,
        team: 'india'
    },
    3:{
        name: 'James Anderson',
        noMatches: 379,
        noCatches: 155,
        economy: 5.19,
        noWickets: 919,
        noFivers: 33,
        team: 'england',
    },
    4:{
        name: 'Adil Rashid',
        noMatches: 199,
        noCatches: 56,
        economy: 5.59,
        noWickets: 293,
        noFivers: 4,
        team: 'england',
    },
    5:{
        name: 'Kagiso Rabada',
        noMatches: 169,
        noCatches: 61,
        economy: 5.62,
        noWickets: 388,
        noFivers: 11,
        team: 'southAfrica',
    },
    6:{
        name: 'Keshav Maharaj',
        noMatches: 59,
        noCatches: 16,
        economy: 4.55,
        noWickets: 154,
        noFivers: 7,
        team: 'southAfrica',
    },
    7:{
        name: 'Mitchell Starc',
        noMatches: 208,
        noCatches: 77,
        economy: 5.33,
        noWickets: 480,
        noFivers: 21,
        team: 'australia',
    },
    8:{
        name: 'Pat Cummins',
        noMatches: 140,
        noCatches: 42,
        economy: 5,
        noWickets: 317,
        noFivers: 6,
        team: 'australia',
    },
    9:{
        name: 'Trent Boult',
        moMatches: 210,
        noCatches: 89,
        economy: 5.36,
        noWickets: 523,
        noFivers: 13,
        team: 'newZealand',
    },
    10:{
        name: 'Tim Southee',
        moMatches: 314,
        noCatches: 146,
        economy: 5.54,
        noWickets: 615,
        noFivers: 16,
        team: 'newZealand',
    },
}

var allRounders = {
    1:{
        name: 'Ravindra Jadeja',
        noMatches: 279,
        strikeRate: 86.87,
        economy: 4.78,
        noWickets: 461,
        avg: 27.89,
        team: 'india',
    },
    2:{
        name: 'Ben Stokes',
        noMatches: 206,
        strikeRate: 96.77,
        economy: 6.03,
        noWickets: 256,
        avg: 32.53,
        team: 'england',
    },
    3:{
        name: 'Chris Morris',
        noMatches: 69,
        strikeRate: 92.87,
        economy: 6.12,
        noWickets: 94,
        avg: 31.77,
        team: 'southAfrica',
    },
    4: {
        name: 'Glenn Maxwell',
        noMatches: 202,
        strikeRate: 113,
        economy: 5.84,
        noWickets: 92,
        avg: 30.38,
        team: 'australia',
    },
    5:{
        name: 'James Neesham',
        noMatches: 116,
        strikeRate: 105.25,
        economy: 6.34,
        noWickets: 103,
        avg: 28.11,
        team: 'newZealand',
    }
}